apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /dotnet(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: task-dotnet-service
                port:
                  number: 80
