apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-golang-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task-golang
  template:
    metadata:
      labels:
        app: task-golang
    spec:
      containers:
      - name: task-golang
        image: wesleyab/cep_service:latest
        ports:
        - containerPort: 8080