apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-python-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task-python
  template:
    metadata:
      labels:
        app: task-python
    spec:
      containers:
      - name: task-python
        image: wesleyab/netcore9:latest
        ports:
        - containerPort: 8084