apiVersion: v1
kind: Service
metadata:
  name: task-dotnet-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: task-dotnet
  ports:
    - name: http
      protocol: TCP
      port: 80           # Porta que o Ingress acessa
      targetPort: 8084   # Porta exposta pelo container
