name: Deploy AKS and Kubernetes Resources

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RG_NAME: ${{ secrets.RG_NAME }}
      AKS_NAME: ${{ secrets.AKS_NAME }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group  $RG_NAME --name $AKS_NAME

      - name: Add ingress-nginx repo
        run: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

      - name: Install ingress-nginx
        run: helm install ingress-nginx ingress-nginx/ingress-nginx || helm upgrade ingress-nginx ingress-nginx/ingress-nginx

      - name: Apply Kubernetes manifests - Deployment
        run: kubectl apply -f K8S/Deployment/

      - name: Apply Kubernetes manifests - Service
        run: kubectl apply -f K8S/Service/

      - name: Apply Kubernetes manifests - Ingress
        run: kubectl apply -f K8S/Ingress/

      - name: Check Pods
        run: kubectl get pods

      - name: Check Deployments
        run: kubectl get deployments

      - name: Check Services
        run: kubectl get services

      - name: Check Ingress
        run: kubectl get ingress
